apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: robotshop
  region: us-west-2

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: xray-daemon
      # if no namespace is set, "default" will be used;
      # the namespace will be created if it doesn't exist already
      namespace: robotshop
      labels: {aws-usage: "application"}
    attachPolicyARNs:
    - "arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess"
  - metadata:
      name: cluster-autoscaler
      namespace: kube-system
      labels: {aws-usage: "cluster-ops"}
    attachPolicy:
      Version: "2012-10-17"
      Statement:
      - Effect: Allow
        Action:
        - "autoscaling:DescribeAutoScalingGroups"
        - "autoscaling:DescribeAutoScalingInstances"
        - "autoscaling:DescribeLaunchConfigurations"
        - "autoscaling:DescribeTags"
        - "autoscaling:SetDesiredCapacity"
        - "autoscaling:TerminateInstanceInAutoScalingGroup"
        Resource: '*'

# Use the encryption key from the CLI
#secretsEncryption:
#  keyARN: "arn:aws:kms:us-west-2:164382793440:key/751f1d85-43fd-4be4-835d-906189f64c8c"

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]