apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"
  namespace: robotshop
  name: cart
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    service: cart
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: robotshop
  name: cart
  labels:
    service: cart
spec:
  replicas: 1
  selector:
    matchLabels:
      service: cart
  template:
    metadata:
      labels:
        service: cart
    spec:
      {{ if .Values.psp.enabled }}
      serviceAccountName: robot-shop
      {{ end }}
      containers:
      - name: cart
        image: {{ .Values.image.repo }}/cart:{{ .Values.image.version }}
        imagePullPolicy: Always
        env:
          - name: NODE_ENV
            value: production
          - name: AWS_XRAY_DAEMON_ADDRESS
            value: 'xray-service.robotshop:2000'
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi